name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with Pytest
        run: |
          pytest --junitxml=pytest-report.xml

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ./pytest-report.xml
          retention-days: 7
